package com.xworkz.chalk;
import com.xworkz.chalk.chalks.Chalk;
public class ChalkRunner {
    public static void main(String[] args) {
        System.out.println("main started");
        Chalk chalk1 = new Chalk();
        chalk1.setChalkColor("White");
        chalk1.setChalkMaterial("Calcium Carbonate");
        chalk1.setChalkLength(10);
        chalk1.setDustless(true);
        chalk1.setChalkWeight(0.5);
        chalk1.setChalkUsage("Educational");
        chalk1.setChalkBrand("Crayola");
        String chalk1Color = chalk1.getChalkColor();
        System.out.println("Chalk Color: " + chalk1Color);
        String chalk1Material = chalk1.getChalkMaterial();
        System.out.println("Chalk Material: " + chalk1Material);
        int chalk1Length = chalk1.getChalkLength();
        System.out.println("Chalk Length: " + chalk1Length);
        boolean chalk1Dustless = chalk1.getDustless();
        System.out.println("Is Dustless: " + chalk1Dustless);
        double chalk1Weight = chalk1.getChalkWeight();
        System.out.println("Chalk Weight: " + chalk1Weight + " grams");
        String chalk1Usage = chalk1.getChalkUsage();
        System.out.println("Chalk Usage: " + chalk1Usage);
        String chalk1Brand = chalk1.getChalkBrand();
        System.out.println("Chalk Brand: " + chalk1Brand);
        System.out.println("*******Complete*********");

        Chalk chalk2 = new Chalk();
        chalk2.setChalkColor("Yellow");
        chalk2.setChalkMaterial("Gypsum");
        chalk2.setChalkLength(8);
        chalk2.setDustless(false);
        chalk2.setChalkWeight(0.4);
        chalk2.setChalkUsage("Artistic");
        chalk2.setChalkBrand("Faber-Castell");
        String chalk2Color = chalk2.getChalkColor();
        System.out.println("Chalk Color: " + chalk2Color);
        String chalk2Material = chalk2.getChalkMaterial();
        System.out.println("Chalk Material: " + chalk2Material);
        int chalk2Length = chalk2.getChalkLength();
        System.out.println("Chalk Length: " + chalk2Length);
        boolean chalk2Dustless = chalk2.getDustless();
        System.out.println("Is Dustless: " + chalk2Dustless);
        double chalk2Weight = chalk2.getChalkWeight();
        System.out.println("Chalk Weight: " + chalk2Weight + " grams");
        String chalk2Usage = chalk2.getChalkUsage();
        System.out.println("Chalk Usage: " + chalk2Usage);
        String chalk2Brand = chalk2.getChalkBrand();
        System.out.println("Chalk Brand: " + chalk2Brand);
        System.out.println("*******Complete*********");

        Chalk chalk3 = new Chalk();
        chalk3.setChalkColor("Blue");
        chalk3.setChalkMaterial("Clay");
        chalk3.setChalkLength(12);
        chalk3.setDustless(true);
        chalk3.setChalkWeight(0.6);
        chalk3.setChalkUsage("Industrial");
        chalk3.setChalkBrand("Camlin");
        String chalk3Color = chalk3.getChalkColor();
        System.out.println("Chalk Color: " + chalk3Color);
        String chalk3Material = chalk3.getChalkMaterial();
        System.out.println("Chalk Material: " + chalk3Material);
        int chalk3Length = chalk3.getChalkLength();
        System.out.println("Chalk Length: " + chalk3Length);
        boolean chalk3Dustless = chalk3.getDustless();
        System.out.println("Is Dustless: " + chalk3Dustless);
        double chalk3Weight = chalk3.getChalkWeight();
        System.out.println("Chalk Weight: " + chalk3Weight + " grams");
        String chalk3Usage = chalk3.getChalkUsage();
        System.out.println("Chalk Usage: " + chalk3Usage);
        String chalk3Brand = chalk3.getChalkBrand();
        System.out.println("Chalk Brand: " + chalk3Brand);
        System.out.println("*******Complete*********");

        Chalk chalk4 = new Chalk();
        chalk4.setChalkColor("Green");
        chalk4.setChalkMaterial("Calcium Sulfate");
        chalk4.setChalkLength(15);
        chalk4.setDustless(false);
        chalk4.setChalkWeight(0.7);
        chalk4.setChalkUsage("Construction");
        chalk4.setChalkBrand("Staedtler");
        String chalk4Color = chalk4.getChalkColor();
        System.out.println("Chalk Color: " + chalk4Color);
        String chalk4Material = chalk4.getChalkMaterial();
        System.out.println("Chalk Material: " + chalk4Material);
        int chalk4Length = chalk4.getChalkLength();
        System.out.println("Chalk Length: " + chalk4Length);
        boolean chalk4Dustless = chalk4.getDustless();
        System.out.println("Is Dustless: " + chalk4Dustless);
        double chalk4Weight = chalk4.getChalkWeight();
        System.out.println("Chalk Weight: " + chalk4Weight + " grams");
        String chalk4Usage = chalk4.getChalkUsage();
        System.out.println("Chalk Usage: " + chalk4Usage);
        String chalk4Brand = chalk4.getChalkBrand();
        System.out.println("Chalk Brand: " + chalk4Brand);
        System.out.println("*******Complete*********");

        Chalk chalk5 = new Chalk();
        chalk5.setChalkColor("Red");
        chalk5.setChalkMaterial("Plaster of Paris");
        chalk5.setChalkLength(9);
        chalk5.setDustless(true);
        chalk5.setChalkWeight(0.3);
        chalk5.setChalkUsage("Creative Writing");
        chalk5.setChalkBrand("Classmate");
        String chalk5Color = chalk5.getChalkColor();
        System.out.println("Chalk Color: " + chalk5Color);
        String chalk5Material = chalk5.getChalkMaterial();
        System.out.println("Chalk Material: " + chalk5Material);
        int chalk5Length = chalk5.getChalkLength();
        System.out.println("Chalk Length: " + chalk5Length);
        boolean chalk5Dustless = chalk5.getDustless();
        System.out.println("Is Dustless: " + chalk5Dustless);
        double chalk5Weight = chalk5.getChalkWeight();
        System.out.println("Chalk Weight: " + chalk5Weight + " grams");
        String chalk5Usage = chalk5.getChalkUsage();
        System.out.println("Chalk Usage: " + chalk5Usage);
        String chalk5Brand = chalk5.getChalkBrand();
        System.out.println("Chalk Brand: " + chalk5Brand);
        System.out.println("*******Complete*********");

        System.out.println("main ended");
    }
}
