package com.xworkz.paint;
import com.xworkz.paint.paints.Paint;
public class PaintRunner {
    public static void main(String[] args) {
        System.out.println("main Stated");
        Paint paint1 = new Paint();
        paint1.setPaintId(12);
        paint1.setPaintBrand("ASIAN PAINTS");
        paint1.setPaintColour("Red");
        paint1.setPaintQuantity(250);
        paint1.setPaintPrice(325.90);
        int paintId = paint1.getPaintId();
        System.out.println("the paint id is:"+paintId);
        double paintPrice = paint1.getPaintPrice();
        System.out.println("the paint id is:"+paintPrice);
        String paintBrand = paint1.getPaintBrand();
        System.out.println("the paint id is:"+paintBrand);
        String paintColour = paint1.getPaintColour();
        System.out.println("the paint id is:"+paintColour);
        int paintQuantity = paint1.getPaintQuantity();
        System.out.println("the paint id is:"+paintQuantity);
        System.out.println("*******Complete*********");

        Paint paint2 = new Paint();
        paint2.setPaintId(45);
        paint2.setPaintBrand("DULUX");
        paint2.setPaintColour("Blue");
        paint2.setPaintQuantity(500);
        paint2.setPaintPrice(450.75);
        int paintId2 = paint2.getPaintId();
        System.out.println("the paint id is:" + paintId2);
        double paintPrice2 = paint2.getPaintPrice();
        System.out.println("the paint price is:" + paintPrice2);
        String paintBrand2 = paint2.getPaintBrand();
        System.out.println("the paint brand is:" + paintBrand2);
        String paintColour2 = paint2.getPaintColour();
        System.out.println("the paint colour is:" + paintColour2);
        int paintQuantity2 = paint2.getPaintQuantity();
        System.out.println("the paint quantity is:" + paintQuantity2);
        System.out.println("*******Complete*********");

        Paint paint3 = new Paint();
        paint3.setPaintId(78);
        paint3.setPaintBrand("NEROLAC");
        paint3.setPaintColour("Green");
        paint3.setPaintQuantity(750);
        paint3.setPaintPrice(600.30);
        int paintId3 = paint3.getPaintId();
        System.out.println("the paint id is:" + paintId3);
        double paintPrice3 = paint3.getPaintPrice();
        System.out.println("the paint price is:" + paintPrice3);
        String paintBrand3 = paint3.getPaintBrand();
        System.out.println("the paint brand is:" + paintBrand3);
        String paintColour3 = paint3.getPaintColour();
        System.out.println("the paint colour is:" + paintColour3);
        int paintQuantity3 = paint3.getPaintQuantity();
        System.out.println("the paint quantity is:" + paintQuantity3);
        System.out.println("*******Complete*********");

        Paint paint4 = new Paint();
        paint4.setPaintId(101);
        paint4.setPaintBrand("BERGER");
        paint4.setPaintColour("Yellow");
        paint4.setPaintQuantity(1000);
        paint4.setPaintPrice(725.50);
        int paintId4 = paint4.getPaintId();
        System.out.println("the paint id is:" + paintId4);
        double paintPrice4 = paint4.getPaintPrice();
        System.out.println("the paint price is:" + paintPrice4);
        String paintBrand4 = paint4.getPaintBrand();
        System.out.println("the paint brand is:" + paintBrand4);
        String paintColour4 = paint4.getPaintColour();
        System.out.println("the paint colour is:" + paintColour4);
        int paintQuantity4 = paint4.getPaintQuantity();
        System.out.println("the paint quantity is:" + paintQuantity4);
        System.out.println("*******Complete*********");

        Paint paint5 = new Paint();
        paint5.setPaintId(125);
        paint5.setPaintBrand("SHALIMAR");
        paint5.setPaintColour("Orange");
        paint5.setPaintQuantity(300);
        paint5.setPaintPrice(345.25);
        int paintId5 = paint5.getPaintId();
        System.out.println("the paint id is:" + paintId5);
        double paintPrice5 = paint5.getPaintPrice();
        System.out.println("the paint price is:" + paintPrice5);
        String paintBrand5 = paint5.getPaintBrand();
        System.out.println("the paint brand is:" + paintBrand5);
        String paintColour5 = paint5.getPaintColour();
        System.out.println("the paint colour is:" + paintColour5);
        int paintQuantity5 = paint5.getPaintQuantity();
        System.out.println("the paint quantity is:" + paintQuantity5);
        System.out.println("*******Complete*********");

        Paint paint6 = new Paint();
        paint6.setPaintId(142);
        paint6.setPaintBrand("AKZONOBEL");
        paint6.setPaintColour("Purple");
        paint6.setPaintQuantity(700);
        paint6.setPaintPrice(580.65);
        int paintId6 = paint6.getPaintId();
        System.out.println("the paint id is:" + paintId6);
        double paintPrice6 = paint6.getPaintPrice();
        System.out.println("the paint price is:" + paintPrice6);
        String paintBrand6 = paint6.getPaintBrand();
        System.out.println("the paint brand is:" + paintBrand6);
        String paintColour6 = paint6.getPaintColour();
        System.out.println("the paint colour is:" + paintColour6);
        int paintQuantity6 = paint6.getPaintQuantity();
        System.out.println("the paint quantity is:" + paintQuantity6);
        System.out.println("*******Complete*********");

        Paint paint7 = new Paint();
        paint7.setPaintId(160);
        paint7.setPaintBrand("JOTUN");
        paint7.setPaintColour("Black");
        paint7.setPaintQuantity(450);
        paint7.setPaintPrice(510.90);
        int paintId7 = paint7.getPaintId();
        System.out.println("the paint id is:" + paintId7);
        double paintPrice7 = paint7.getPaintPrice();
        System.out.println("the paint price is:" + paintPrice7);
        String paintBrand7 = paint7.getPaintBrand();
        System.out.println("the paint brand is:" + paintBrand7);
        String paintColour7 = paint7.getPaintColour();
        System.out.println("the paint colour is:" + paintColour7);
        int paintQuantity7 = paint7.getPaintQuantity();
        System.out.println("the paint quantity is:" + paintQuantity7);
        System.out.println("*******Complete*********");

        System.out.println("main Ended");
    }
}
