class BellRunner{
public static void main(String output[]){
 Bell market99 = new Bell();
 market99.bellSound="Ding Dong";
 market99.bellTone ="Sharp and Clear";
 market99.bellPurpose="Calling for attention";
 System.out.println("the market99 bellSound is: "+market99.bellSound);
 System.out.println("the market99 bellTone  is: "+market99.bellTone );
 System.out.println("the market99 bellPurpose is: "+market99.bellPurpose);
 System.out.println("*****<><><><><>*****");
 Bell incrizma = new Bell("Chime","Harmonic","Marking time");
 System.out.println("the incrizma bellSound is: "+incrizma.bellSound);
 System.out.println("the incrizma bellTone  is: "+incrizma.bellTone );
 System.out.println("the incrizma bellPurpose is: "+incrizma.bellPurpose);
 System.out.println("*****<><><><><>*****");
 Bell bs_Amor  = new Bell();
 bs_Amor.bellSound="Ting";
 bs_Amor.bellTone ="Echoing";
 bs_Amor.bellPurpose="Celebration";
 System.out.println("the bs_Amor bellSound is: "+bs_Amor.bellSound);
 System.out.println("the bs_Amor bellTone  is: "+bs_Amor.bellTone );
 System.out.println("the bs_Amor bellPurpose is: "+bs_Amor.bellPurpose);
 System.out.println("*****<><><><><>*****");
 Bell skyWalk = new Bell("Bong","Mellow and Warm","Alarm or Warning");
 System.out.println("the skyWalk bellSound is: "+skyWalk.bellSound);
 System.out.println("the skyWalk bellTone  is: "+skyWalk.bellTone );
 System.out.println("the skyWalk bellPurpose is: "+skyWalk.bellPurpose);
 System.out.println("*****<><><><><>*****");
 Bell varEesha = new Bell();
 varEesha.bellSound="Clang";
 varEesha.bellTone ="Bold and Metallic";
 varEesha.bellPurpose="Ceremonial use";
 System.out.println("the varEesha bellSound is: "+varEesha.bellSound);
 System.out.println("the varEesha bellTone  is: "+varEesha.bellTone );
 System.out.println("the varEesha bellPurpose is: "+varEesha.bellPurpose);
 System.out.println("*****<><><><><>*****");
 Bell ikea = new Bell("Melody Ring","Soft and Subtle","Guiding travelers");
 System.out.println("the ikea bellSound is: "+ikea.bellSound);
 System.out.println("the ikea bellTone  is: "+ikea.bellTone );
 System.out.println("the ikea bellPurpose is: "+ikea.bellPurpose);
 System.out.println("*****<><><><><>*****");
 Bell sphinx = new Bell();
 sphinx.bellSound="High-pitched and Crisp";
 sphinx.bellTone ="BreakResistant";
 sphinx.bellPurpose="Musical instrument";
 System.out.println("the sphinx bellSound is: "+sphinx.bellSound);
 System.out.println("the sphinx bellTone  is: "+sphinx.bellTone );
 System.out.println("the sphinx bellPurpose is: "+sphinx.bellPurpose);
 System.out.println("*****<><><><><>*****");
 Bell tiedRibbon = new Bell("Soft Tinkle","Deep and Resonant","Decoration");
 System.out.println("the tiedRibbon bellSound is: "+tiedRibbon.bellSound);
 System.out.println("the tiedRibbon bellTone  is: "+tiedRibbon.bellTone );
 System.out.println("the tiedRibbon bellPurpose is: "+tiedRibbon.bellPurpose);
 System.out.println("*****<><><><><>*****");
}
}