class CarryBagRunner{
public static void main(String output[]){
CarryBag Samsonite = new CarryBag();
Samsonite.bagCapacity=5;
Samsonite.bagClosure ="Roll-top closure";
Samsonite.bagType="Reusable shopping bag";
System.out.println("the Samsonite bagCapacity is: "+Samsonite.bagCapacity);
System.out.println("the Samsonite bagClosure  is: "+Samsonite.bagClosure );
System.out.println("the Samsonite bagType is: "+Samsonite.bagType);
System.out.println("*****<><><><><>*****");
CarryBag americanTourister = new CarryBag(16,"Hook-and-loop fastening","Clutch bag");
System.out.println("the americanTourister bagCapacity is: "+americanTourister.bagCapacity);
System.out.println("the americanTourister bagClosure  is: "+americanTourister.bagClosure );
System.out.println("the americanTourister bagType is: "+americanTourister.bagType);
System.out.println("*****<><><><><>*****");
CarryBag skybags  = new CarryBag();
skybags.bagCapacity=13;
skybags.bagClosure ="Twist-lock closure";
skybags.bagType="Drawstring bag";
System.out.println("the skybags bagCapacity is: "+skybags.bagCapacity);
System.out.println("the skybags bagClosure  is: "+skybags.bagClosure );
System.out.println("the skybags bagType is: "+skybags.bagType);
System.out.println("*****<><><><><>*****");
CarryBag vip = new CarryBag(11,"Flap with magnetic snap","Duffel bag");
System.out.println("the vip bagCapacity is: "+vip.bagCapacity);
System.out.println("the vip bagClosure  is: "+vip.bagClosure );
System.out.println("the vip bagType is: "+vip.bagType);
System.out.println("*****<><><><><>*****");
CarryBag safari = new CarryBag();
safari.bagCapacity=9;
safari.bagClosure ="Button clasp";
safari.bagType="Messenger bag";
System.out.println("the safari bagCapacity is: "+safari.bagCapacity);
System.out.println("the safari bagClosure  is: "+safari.bagClosure );
System.out.println("the safari bagType is: "+safari.bagType);
System.out.println("*****<><><><><>*****");
CarryBag Baggit = new CarryBag(15,"Drawstring closure","Backpack");
System.out.println("the Baggit bagCapacity is: "+Baggit.bagCapacity);
System.out.println("the Baggit bagClosure  is: "+Baggit.bagClosure );
System.out.println("the Baggit bagType is: "+Baggit.bagType);
System.out.println("*****<><><><><>*****");
CarryBag wildcraft = new CarryBag();
wildcraft.bagCapacity=12;
wildcraft.bagClosure ="Velcro fastening";
wildcraft.bagType="Tote bag";
System.out.println("the wildcraft bagCapacity is: "+wildcraft.bagCapacity);
System.out.println("the wildcraft bagClosure  is: "+wildcraft.bagClosure );
System.out.println("the wildcraft bagType is: "+wildcraft.bagType);
System.out.println("*****<><><><><>*****");
CarryBag caprese = new CarryBag(8,"Zipper closure","Sling bag");
System.out.println("the caprese bagCapacity is: "+caprese.bagCapacity);
System.out.println("the caprese bagClosure  is: "+caprese.bagClosure );
System.out.println("the caprese bagType is: "+caprese.bagType);
System.out.println("*****<><><><><>*****");
}
}