class PhotoFrameRunner{
public static void main(String output[]){
 PhotoFrame Photo1 = new PhotoFrame();
 Photo1.displayDeck="Slideshow mode";
 Photo1.pixelPerfection ="Ultra HD Resolution";
 Photo1.snapshotShowcase="festival collection";
 System.out.println("the Photo1 displayDeck is: "+Photo1.displayDeck);
 System.out.println("the Photo1 pixelPerfection  is: "+Photo1.pixelPerfection );
 System.out.println("the Photo1 snapshotShowcase is: "+Photo1.snapshotShowcase);
 System.out.println("*****<><><><><>*****");
 PhotoFrame Photo2 = new PhotoFrame("Digital mode","Full HD","annivasary collection");
 System.out.println("the Photo2 displayDeck is: "+Photo2.displayDeck);
 System.out.println("the Photo2 pixelPerfection  is: "+Photo2.pixelPerfection );
 System.out.println("the Photo2 snapshotShowcase is: "+Photo2.snapshotShowcase);
 System.out.println("*****<><><><><>*****");
 PhotoFrame Photo3  = new PhotoFrame();
 Photo3.displayDeck="Slideshow mode";
 Photo3.pixelPerfection ="Retina Display";
 Photo3.snapshotShowcase="pets collection";
 System.out.println("the Photo3 displayDeck is: "+Photo3.displayDeck);
 System.out.println("the Photo3 pixelPerfection  is: "+Photo3.pixelPerfection );
 System.out.println("the Photo3 snapshotShowcase is: "+Photo3.snapshotShowcase);
 System.out.println("*****<><><><><>*****");
 PhotoFrame Photo4 = new PhotoFrame("Digital mode","Retina Display","playing games collection");
 System.out.println("the Photo4 displayDeck is: "+Photo4.displayDeck);
 System.out.println("the Photo4 pixelPerfection  is: "+Photo4.pixelPerfection );
 System.out.println("the Photo4 snapshotShowcase is: "+Photo4.snapshotShowcase);
 System.out.println("*****<><><><><>*****");
 PhotoFrame Photo5 = new PhotoFrame();
 Photo5.displayDeck="Slideshow mode";
 Photo5.pixelPerfection ="Standard Definition (SD)";
 Photo5.snapshotShowcase="travling collection";
 System.out.println("the Photo5 displayDeck is: "+Photo5.displayDeck);
 System.out.println("the Photo5 pixelPerfection  is: "+Photo5.pixelPerfection );
 System.out.println("the Photo5 snapshotShowcase is: "+Photo5.snapshotShowcase);
 System.out.println("*****<><><><><>*****");
 PhotoFrame Photo6 = new PhotoFrame("Digital mode","Standard Definition(SD)","NewYear collection");
 System.out.println("the Photo6 displayDeck is: "+Photo6.displayDeck);
 System.out.println("the Photo6 pixelPerfection  is: "+Photo6.pixelPerfection );
 System.out.println("the Photo6 snapshotShowcase is: "+Photo6.snapshotShowcase);
 System.out.println("*****<><><><><>*****");
 PhotoFrame Photo8 = new PhotoFrame();
 Photo8.displayDeck="Slideshow mode";
 Photo8.pixelPerfection ="Full HD";
 Photo8.snapshotShowcase="Birthday collection";
 System.out.println("the Photo8 displayDeck is: "+Photo8.displayDeck);
 System.out.println("the Photo8 pixelPerfection  is: "+Photo8.pixelPerfection );
 System.out.println("the Photo8 snapshotShowcase is: "+Photo8.snapshotShowcase);
 System.out.println("*****<><><><><>*****");
 PhotoFrame Photo7 = new PhotoFrame("Digital mode","Ultra HD Resolution","Wedding Collection");
 System.out.println("the Photo7 displayDeck is: "+Photo7.displayDeck);
 System.out.println("the Photo7 pixelPerfection  is: "+Photo7.pixelPerfection );
 System.out.println("the Photo7 snapshotShowcase is: "+Photo7.snapshotShowcase);
 System.out.println("*****<><><><><>*****");
}
}