class Proteinsupplement{
 public static void main(String unflavoured[]){
  System.out.println("--> About this item <--");
  System.out.println("-->27g PROTEIN PER SCOOP: Wellbeing Nutrition Whey Concentrate Protein delivers 27g of protein, 12.7g EAA and 6g of naturally occurring BCAAs per serving that promotes muscle building and faster post-workout recovery.");
  System.out.println("-->ULTRA- PURE, INSTANTIZED & MICROFILTERED: Our non-denatured whey concentrate is filtered using cross flow microfilteration is sourced directly from milk and not a by-product of cheese. It's carefully processed at low temperatures without the use of acids or bleach, ensuring a cleaner, more intact protein that preserves natural bioactive peptides & essential nutrients. Instantized with natural emulsifier sunflower lecithin for easy mixing to prevent lumps and clumps");
  System.out.println("-->4B CFU PROBIOTICS FOR GUT FRIENDLY GOODNESS: Clinically proven probiotic strains of Lactobacillus acidophilus and Bifidobacterium longum support better nutrient absorption, improve gut microbiome & boost the body’s natural defenses. ");
  System.out.println("-->BANNED SUBSTANCE & HORMONE FREE: Our premium whey protein concentrate is crafted in a US FDA & NSF registered facility, with every batch rigorously tested for amino spiking, protein concentration, and heavy metals. Our hormone free rBST/rBGH free whey protein is sourced from Europe — the gold standard in quality whey ingredients—for a formula you can trust.");
  System.out.println("-->CLEAN LABEL CERTIFIED, NO HARMFUL CHEMICALS: Proudly awarded for clean label purity our formula is made without any added flavours, artificial sweeteners, preservatives, gums, thickeners, anti-caking agents, anti-foaming agents, amino-spiking agents, heavy metal contamination, adulterants or doping agents.");
 }
}