class SmartWatch{
 static public void main(String durability[]){
   System.out.println("--> About this item <--");
   System.out.println("-->Crystal-Clear Bluetooth Calling: Experience an unmatched hands-free calling experience with industry-first 3-Mic ENC technology, delivering superior noise cancellation for clear, phone-like conversations. Stay connected on the go with Bluetooth calling, make and receive calls directly from your wrist with exceptional clarity, whether you're at home or outdoors. Designed for both men and women, this smartwatch ensures seamless communication with crystal-clear audio quality.");
   System.out.println("-->Premium Metal Body Design with Superior Durability: Crafted with sleek metal body and zinc alloy, this smartwatch combines a premium look with exceptional durability. The scratch-resistant super glass ensures rugged usability, while its impact-resistant design makes it perfect for any adventure. The stunning metal body not only adds a touch of sophistication but also provides robust protection for your active lifestyle.");
   System.out.println("-->Long-Lasting Battery Life for Extended Usage: Stay powered up with an 18-day battery life, backed by a 470mAh large-capacity battery and a low-power chip. Enjoy up to 14 days of heavy usage and 10 days of continuous usage, with a quick 2-hour charging time using the magnetic charging cable. This smartwatch ensures you’re always ready for your next adventure without frequent charging");
   System.out.println("-->140+ Workout Modes with IPX8 Water Resistance: Track multiple workout modes with detailed and accurate metrics. This smartwatch also monitors your heart rate, sleep patterns, SpO2 levels, and female menstrual cycle, making it a comprehensive health and fitness companion for both man & woman.");
   System.out.println("-->Vibrant 2-Inch Large HD Display: Immerse yourself in vivid visuals with a 2-inch HD display, featuring 320 x 380 pixels resolution and 500 nits peak brightness for clear viewing even in sunlight. The 80:20 screen-to-body ratio offers a larger, smoother view of your activities, tracking data, and notifications, delivering a truly premium experience on your wrist.");
 }
}