class SoapRunner{
public static void main(String output[]){
 Soap lux = new Soap();
 lux.latherQuality="High Lather";
 lux.ecoFriendly ="NO";
 lux.bubbleCount=1984;
 System.out.println("the lux latherQuality is: "+lux.latherQuality);
 System.out.println("the lux ecoFriendly  is: "+lux.ecoFriendly );
 System.out.println("the lux bubbleCount is: "+lux.bubbleCount);
 System.out.println("*****<><><><><>*****");
 Soap loccitane = new Soap("Silky Lather","YES",125);
 System.out.println("the loccitane latherQuality is: "+loccitane.latherQuality);
 System.out.println("the loccitane ecoFriendly  is: "+loccitane.ecoFriendly );
 System.out.println("the loccitane bubbleCount is: "+loccitane.bubbleCount);
 System.out.println("*****<><><><><>*****");
 Soap drBronners  = new Soap();
 drBronners.latherQuality="Dense Lather";
 drBronners.ecoFriendly ="YES";
 drBronners.bubbleCount=1454;
 System.out.println("the drBronners latherQuality is: "+drBronners.latherQuality);
 System.out.println("the drBronners ecoFriendly  is: "+drBronners.ecoFriendly );
 System.out.println("the drBronners bubbleCount is: "+drBronners.bubbleCount);
 System.out.println("*****<><><><><>*****");
 Soap pears = new Soap("Bubbly Lather ","NO",1256);
 System.out.println("the pears latherQuality is: "+pears.latherQuality);
 System.out.println("the pears ecoFriendly  is: "+pears.ecoFriendly );
 System.out.println("the pears bubbleCount is: "+pears.bubbleCount);
 System.out.println("*****<><><><><>*****");
 Soap lifebuoy = new Soap();
 lifebuoy.latherQuality="Creamy lather";
 lifebuoy.ecoFriendly ="yes";
 lifebuoy.bubbleCount=345;
 System.out.println("the lifebuoy latherQuality is: "+lifebuoy.latherQuality);
 System.out.println("the lifebuoy ecoFriendly  is: "+lifebuoy.ecoFriendly );
 System.out.println("the lifebuoy bubbleCount is: "+lifebuoy.bubbleCount);
 System.out.println("*****<><><><><>*****");
 Soap santhurSandal = new Soap("Medium Lather","NO",456);
 System.out.println("the santhurSandal latherQuality is: "+santhurSandal.latherQuality);
 System.out.println("the santhurSandal ecoFriendly  is: "+santhurSandal.ecoFriendly );
 System.out.println("the santhurSandal bubbleCount is: "+santhurSandal.bubbleCount);
 System.out.println("*****<><><><><>*****");
 Soap medimix = new Soap();
 medimix.latherQuality="Low Lather";
 medimix.ecoFriendly ="YES";
 medimix.bubbleCount=234;
 System.out.println("the medimix latherQuality is: "+medimix.latherQuality);
 System.out.println("the medimix ecoFriendly  is: "+medimix.ecoFriendly );
 System.out.println("the medimix bubbleCount is: "+medimix.bubbleCount);
 System.out.println("*****<><><><><>*****");
 Soap rexsona = new Soap("Residual-Free Lather","NO",62);
 System.out.println("the rexsona latherQuality is: "+rexsona.latherQuality);
 System.out.println("the rexsona ecoFriendly  is: "+rexsona.ecoFriendly );
 System.out.println("the rexsona bubbleCount is: "+rexsona.bubbleCount);
 System.out.println("*****<><><><><>*****");
}
}