class VaseRunner{
public static void main(String output[]){
 Vase market99 = new Vase();
 market99.VasePattern="AnimalPrint";
 market99.VaseFeatures ="FadeResistant";
 market99.VaseStyle="Farmhouse";
 System.out.println("the market99 VasePattern is: "+market99.VasePattern);
 System.out.println("the market99 VaseFeatures  is: "+market99.VaseFeatures );
 System.out.println("the market99 VaseStyle is: "+market99.VaseStyle);
 System.out.println("*****<><><><><>*****");
 Vase incrizma = new Vase("Argyle","RustResistance","French");
 System.out.println("the incrizma VasePattern is: "+incrizma.VasePattern);
 System.out.println("the incrizma VaseFeatures  is: "+incrizma.VaseFeatures );
 System.out.println("the incrizma VaseStyle is: "+incrizma.VaseStyle);
 System.out.println("*****<><><><><>*****");
 Vase bs_Amor  = new Vase();
 bs_Amor.VasePattern="Fruit";
 bs_Amor.VaseFeatures ="UV Resistance";
 bs_Amor.VaseStyle="Classic";
 System.out.println("the bs_Amor VasePattern is: "+bs_Amor.VasePattern);
 System.out.println("the bs_Amor VaseFeatures  is: "+bs_Amor.VaseFeatures );
 System.out.println("the bs_Amor VaseStyle is: "+bs_Amor.VaseStyle);
 System.out.println("*****<><><><><>*****");
 Vase skyWalk = new Vase("Cartoon","Ligthweigth","Casual");
 System.out.println("the skyWalk VasePattern is: "+skyWalk.VasePattern);
 System.out.println("the skyWalk VaseFeatures  is: "+skyWalk.VaseFeatures );
 System.out.println("the skyWalk VaseStyle is: "+skyWalk.VaseStyle);
 System.out.println("*****<><><><><>*****");
 Vase varEesha = new Vase();
 varEesha.VasePattern="Geometric";
 varEesha.VaseFeatures ="HighTransparency";
 varEesha.VaseStyle="Bohemian";
 System.out.println("the varEesha VasePattern is: "+varEesha.VasePattern);
 System.out.println("the varEesha VaseFeatures  is: "+varEesha.VaseFeatures );
 System.out.println("the varEesha VaseStyle is: "+varEesha.VaseStyle);
 System.out.println("*****<><><><><>*****");
 Vase ikea = new Vase("Marble","ChipResistant","ArtDeco");
 System.out.println("the ikea VasePattern is: "+ikea.VasePattern);
 System.out.println("the ikea VaseFeatures  is: "+ikea.VaseFeatures );
 System.out.println("the ikea VaseStyle is: "+ikea.VaseStyle);
 System.out.println("*****<><><><><>*****");
 Vase sphinx = new Vase();
 sphinx.VasePattern="Striped";
 sphinx.VaseFeatures ="BreakResistant";
 sphinx.VaseStyle="Glow-in-the-dark Vase";
 System.out.println("the sphinx VasePattern is: "+sphinx.VasePattern);
 System.out.println("the sphinx VaseFeatures  is: "+sphinx.VaseFeatures );
 System.out.println("the sphinx VaseStyle is: "+sphinx.VaseStyle);
 System.out.println("*****<><><><><>*****");
 Vase tiedRibbon = new Vase("PolkaDots","Antique-slip Base","Antique");
 System.out.println("the tiedRibbon VasePattern is: "+tiedRibbon.VasePattern);
 System.out.println("the tiedRibbon VaseFeatures  is: "+tiedRibbon.VaseFeatures );
 System.out.println("the tiedRibbon VaseStyle is: "+tiedRibbon.VaseStyle);
 System.out.println("*****<><><><><>*****");
}
}