package com.xworkz.watertank;
import com.xworkz.watertank.tanks.WaterTank;

public class WatertankRunner {
    public static void main(String[] args) {
        System.out.println("Main Started");
        WaterTank tank1 = new WaterTank();
        tank1.setTankWarrantyYears(5);
        tank1.setUVResistance(true);
        tank1.setAntiAlgae(true);
        tank1.setTankUsageType("Residential");
        tank1.setInsulated(true);
        tank1.setTankShape("Cylindrical");
        tank1.setTankWeight(50.75);
        int tank1WarrantyYears = tank1.getTankWarrantyYears();
        System.out.println("Tank Warranty Years: " + tank1WarrantyYears);
        boolean tank1UVResistance = tank1.getUVResistance();
        System.out.println("UV Resistant: " + tank1UVResistance);
        boolean tank1AntiAlgae = tank1.getAntiAlgae();
        System.out.println("Anti-Algae: " + tank1AntiAlgae);
        String tank1UsageType = tank1.getTankUsageType();
        System.out.println("Tank Usage Type: " + tank1UsageType);
        boolean tank1Insulated = tank1.getInsulated();
        System.out.println("Insulated: " + tank1Insulated);
        String tank1Shape = tank1.getTankShape();
        System.out.println("Tank Shape: " + tank1Shape);
        double tank1Weight = tank1.getTankWeight();
        System.out.println("Tank Weight: " + tank1Weight);
        System.out.println("*******Complete*********");

        WaterTank tank2 = new WaterTank();
        tank2.setTankWarrantyYears(10);
        tank2.setUVResistance(false);
        tank2.setAntiAlgae(false);
        tank2.setTankUsageType("Industrial");
        tank2.setInsulated(false);
        tank2.setTankShape("Rectangular");
        tank2.setTankWeight(75.20);
        int tank2WarrantyYears = tank2.getTankWarrantyYears();
        System.out.println("Tank Warranty Years: " + tank2WarrantyYears);
        boolean tank2UVResistance = tank2.getUVResistance();
        System.out.println("UV Resistant: " + tank2UVResistance);
        boolean tank2AntiAlgae = tank2.getAntiAlgae();
        System.out.println("Anti-Algae: " + tank2AntiAlgae);
        String tank2UsageType = tank2.getTankUsageType();
        System.out.println("Tank Usage Type: " + tank2UsageType);
        boolean tank2Insulated = tank2.getInsulated();
        System.out.println("Insulated: " + tank2Insulated);
        String tank2Shape = tank2.getTankShape();
        System.out.println("Tank Shape: " + tank2Shape);
        double tank2Weight = tank2.getTankWeight();
        System.out.println("Tank Weight: " + tank2Weight);
        System.out.println("*******Complete*********");

        WaterTank tank3 = new WaterTank();
        tank3.setTankWarrantyYears(8);
        tank3.setUVResistance(true);
        tank3.setAntiAlgae(false);
        tank3.setTankUsageType("Agricultural");
        tank3.setInsulated(true);
        tank3.setTankShape("Round");
        tank3.setTankWeight(45.50);
        int tank3WarrantyYears = tank3.getTankWarrantyYears();
        System.out.println("Tank Warranty Years: " + tank3WarrantyYears);
        boolean tank3UVResistance = tank3.getUVResistance();
        System.out.println("UV Resistant: " + tank3UVResistance);
        boolean tank3AntiAlgae = tank3.getAntiAlgae();
        System.out.println("Anti-Algae: " + tank3AntiAlgae);
        String tank3UsageType = tank3.getTankUsageType();
        System.out.println("Tank Usage Type: " + tank3UsageType);
        boolean tank3Insulated = tank3.getInsulated();
        System.out.println("Insulated: " + tank3Insulated);
        String tank3Shape = tank3.getTankShape();
        System.out.println("Tank Shape: " + tank3Shape);
        double tank3Weight = tank3.getTankWeight();
        System.out.println("Tank Weight: " + tank3Weight);
        System.out.println("*******Complete*********");

        WaterTank tank4 = new WaterTank();
        tank4.setTankWarrantyYears(3);
        tank4.setUVResistance(false);
        tank4.setAntiAlgae(true);
        tank4.setTankUsageType("Commercial");
        tank4.setInsulated(false);
        tank4.setTankShape("Square");
        tank4.setTankWeight(80.30);
        int tank4WarrantyYears = tank4.getTankWarrantyYears();
        System.out.println("Tank Warranty Years: " + tank4WarrantyYears);
        boolean tank4UVResistance = tank4.getUVResistance();
        System.out.println("UV Resistant: " + tank4UVResistance);
        boolean tank4AntiAlgae = tank4.getAntiAlgae();
        System.out.println("Anti-Algae: " + tank4AntiAlgae);
        String tank4UsageType = tank4.getTankUsageType();
        System.out.println("Tank Usage Type: " + tank4UsageType);
        boolean tank4Insulated = tank4.getInsulated();
        System.out.println("Insulated: " + tank4Insulated);
        String tank4Shape = tank4.getTankShape();
        System.out.println("Tank Shape: " + tank4Shape);
        double tank4Weight = tank4.getTankWeight();
        System.out.println("Tank Weight: " + tank4Weight);
        System.out.println("*******Complete*********");

        WaterTank tank5 = new WaterTank();
        tank5.setTankWarrantyYears(7);
        tank5.setUVResistance(true);
        tank5.setAntiAlgae(true);
        tank5.setTankUsageType("Industrial");
        tank5.setInsulated(false);
        tank5.setTankShape("Elliptical");
        tank5.setTankWeight(90.75);
        int tankWarrantyYears = tank5.getTankWarrantyYears();
        System.out.println("Tank Warranty Years: " + tankWarrantyYears);
        boolean uvResistance = tank5.getUVResistance();
        System.out.println("UV Resistant: " + uvResistance);
        boolean antiAlgae = tank5.getAntiAlgae();
        System.out.println("Anti-Algae: " + antiAlgae);
        String tankUsageType = tank5.getTankUsageType();
        System.out.println("Tank Usage Type: " + tankUsageType);
        boolean insulated = tank5.getInsulated();
        System.out.println("Insulated: " + insulated);
        String tankShape = tank5.getTankShape();
        System.out.println("Tank Shape: " + tankShape);
        double tankWeight = tank5.getTankWeight();
        System.out.println("Tank Weight: " + tankWeight);
        System.out.println("*******Complete*********");

        System.out.println("Main Ended");
    }
}