package com.xworkz.crop;
import com.xworkz.crop.field.Crop;
    public class CropRunner {
        public static void main(String[] args) {
            Crop crop1 = new Crop();
            crop1.setCropName("Wheat");
            crop1.setAreaCultivated(120.5);
            crop1.setSeason("Winter");
            crop1.setYieldPerHectare(4.2);
            crop1.setSoilType("Loamy");
            crop1.setIrrigationType("Drip");
            crop1.setMarketPrice(1500.75);
            String cropName = crop1.getCropName();
            System.out.println("Crop Name: " + cropName);
            double areaCultivated = crop1.getAreaCultivated();
            System.out.println("Area Cultivated: " + areaCultivated + " hectares");
            String season = crop1.getSeason();
            System.out.println("Season: " + season);
            double yieldPerHectare = crop1.getYieldPerHectare();
            System.out.println("Yield Per Hectare: " + yieldPerHectare + " tons");
            String soilType = crop1.getSoilType();
            System.out.println("Soil Type: " + soilType);
            String irrigationType = crop1.getIrrigationType();
            System.out.println("Irrigation Type: " + irrigationType);
            double marketPrice = crop1.getMarketPrice();
            System.out.println("Market Price: $" + marketPrice + " per ton");

            Crop crop2 = new Crop();
            crop2.setCropName("Rice");
            crop2.setAreaCultivated(200.8);
            crop2.setSeason("Monsoon");
            crop2.setYieldPerHectare(3.7);
            crop2.setSoilType("Clayey");
            crop2.setIrrigationType("Flood");
            crop2.setMarketPrice(1200.50);
            String cropName2 = crop2.getCropName();
            System.out.println("Crop Name: " + cropName2);
            double areaCultivated2 = crop2.getAreaCultivated();
            System.out.println("Area Cultivated: " + areaCultivated2 + " hectares");
            String season2 = crop2.getSeason();
            System.out.println("Season: " + season2);
            double yieldPerHectare2 = crop2.getYieldPerHectare();
            System.out.println("Yield Per Hectare: " + yieldPerHectare2 + " tons");
            String soilType2 = crop2.getSoilType();
            System.out.println("Soil Type: " + soilType2);
            String irrigationType2 = crop2.getIrrigationType();
            System.out.println("Irrigation Type: " + irrigationType2);
            double marketPrice2 = crop2.getMarketPrice();
            System.out.println("Market Price: $" + marketPrice2 + " per ton");

            Crop crop3 = new Crop();
            crop3.setCropName("Corn");
            crop3.setAreaCultivated(150.4);
            crop3.setSeason("Summer");
            crop3.setYieldPerHectare(5.1);
            crop3.setSoilType("Sandy");
            crop3.setIrrigationType("Sprinkler");
            crop3.setMarketPrice(1400.75);
            String cropName3 = crop3.getCropName();
            System.out.println("Crop Name: " + cropName3);
            double areaCultivated3 = crop3.getAreaCultivated();
            System.out.println("Area Cultivated: " + areaCultivated3 + " hectares");
            String season3 = crop3.getSeason();
            System.out.println("Season: " + season3);
            double yieldPerHectare3 = crop3.getYieldPerHectare();
            System.out.println("Yield Per Hectare: " + yieldPerHectare3 + " tons");
            String soilType3 = crop3.getSoilType();
            System.out.println("Soil Type: " + soilType3);
            String irrigationType3 = crop3.getIrrigationType();
            System.out.println("Irrigation Type: " + irrigationType3);
            double marketPrice3 = crop3.getMarketPrice();
            System.out.println("Market Price: $" + marketPrice3 + " per ton");

            Crop crop4 = new Crop();
            crop4.setCropName("Sugarcane");
            crop4.setAreaCultivated(180.3);
            crop4.setSeason("Autumn");
            crop4.setYieldPerHectare(6.2);
            crop4.setSoilType("Loamy");
            crop4.setIrrigationType("Drip");
            crop4.setMarketPrice(1000.30);
            String cropName4 = crop4.getCropName();
            System.out.println("Crop Name: " + cropName4);
            double areaCultivated4 = crop4.getAreaCultivated();
            System.out.println("Area Cultivated: " + areaCultivated4 + " hectares");
            String season4 = crop4.getSeason();
            System.out.println("Season: " + season4);
            double yieldPerHectare4 = crop4.getYieldPerHectare();
            System.out.println("Yield Per Hectare: " + yieldPerHectare4 + " tons");
            String soilType4 = crop4.getSoilType();
            System.out.println("Soil Type: " + soilType4);
            String irrigationType4 = crop4.getIrrigationType();
            System.out.println("Irrigation Type: " + irrigationType4);
            double marketPrice4 = crop4.getMarketPrice();
            System.out.println("Market Price: $" + marketPrice4 + " per ton");

            Crop crop5 = new Crop();
            crop5.setCropName("Cotton");
            crop5.setAreaCultivated(75.5);
            crop5.setSeason("Spring");
            crop5.setYieldPerHectare(2.3);
            crop5.setSoilType("Black Soil");
            crop5.setIrrigationType("Furrow");
            crop5.setMarketPrice(2200.90);
            String cropName5 = crop5.getCropName();
            System.out.println("Crop Name: " + cropName5);
            double areaCultivated5 = crop5.getAreaCultivated();
            System.out.println("Area Cultivated: " + areaCultivated5 + " hectares");
            String season5 = crop5.getSeason();
            System.out.println("Season: " + season5);
            double yieldPerHectare5 = crop5.getYieldPerHectare();
            System.out.println("Yield Per Hectare: " + yieldPerHectare5 + " tons");
            String soilType5 = crop5.getSoilType();
            System.out.println("Soil Type: " + soilType5);
            String irrigationType5 = crop5.getIrrigationType();
            System.out.println("Irrigation Type: " + irrigationType5);
            double marketPrice5 = crop5.getMarketPrice();
            System.out.println("Market Price: $" + marketPrice5 + " per ton");
            System.out.println("*******Complete*********");
        }
    }


